query getTransactions(
  $ascOrder: Boolean
  $skip: Int
  $take: Int
  $selectedBank: String
) {
  transactions: getTransactions(
    ascOrder: $ascOrder
    skip: $skip
    take: $take
    selectedBank: $selectedBank
  ) {
    id
    reference
    amount
    currency
    date
    category {
      name
      color
    }
  }
}
